theme: jekyll-theme-minimal
logo: images/multiwater_logo.PNG
title: MULTIWATER
description: An ESA Sentinel User Preparation (SUP) initiative
plugins:
  - jekyll-toc

related_blog_posts:
  enabled: true
  max_related: 5
